#Configuration File
#Tue Mar 31 13:11:51 CDT 2026
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.38.0.20251204-0849
eclipse.p2.data.area=@config.dir/.p2
eclipse.p2.profile=epp.package.rcp
eclipse.product=org.eclipse.epp.package.rcp.product
org.eclipse.equinox.simpleconfigurator.configUrl=file\:/Users/dreamxia/2025_Dr.Song/ManageCodeClones_IDEPlugins/refactor_server_client/workspace_viz/refactor_plugin/.metadata/.plugins/org.eclipse.pde.core/New_configuration/org.eclipse.equinox.simpleconfigurator/bundles.info
org.eclipse.update.reconcile=false
osgi.bundles=reference\:file\:/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.simpleconfigurator_1.5.700.v20251111-1031.jar@1\:start
osgi.bundles.defaultStartLevel=4
osgi.configuration.cascaded=false
osgi.framework=file\:/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.osgi_3.24.0.v20251126-0427.jar
osgi.framework.extensions=reference\:file\:/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.osgi.compatibility.state_1.3.0.v20251022-1724.jar
osgi.install.area=file\:/Applications/Eclipse.app/Contents/Eclipse/
osgi.instance.area.default=@user.home/Documents/workspace
osgi.splashPath=file\:/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.epp.package.common_4.38.0.20251204-0849
